### ISSUE TITLE
the Sonic chromatic scale.

### ISSUE THREAD

**Issue by SansTheGamingComic** [Chimmiemdp/FNF-FANMADE-CHROMATIC-SCALES#2]
you used MY Sonic chromatic scale that I put onto Funkipedia Mods. either credit me or remove it.

**Comment by Chimmiemdp** [comment]
Aight there, i removed yours and replaced it with my own :)

**Comment by SansTheGamingComic** [comment]
i swear if you used mine to make that one I will be so mad.

**Comment by Chimmiemdp** [comment]
Dawg you did the same thinng as me, Pitch up the sonic exe chromatic. It really aint hard to do 💀

**Comment by SansTheGamingComic** [comment]
i was just making sure jeez.

**Comment by Chimmiemdp** [comment]
K
