### ISSUE TITLE
Some voicebanks have no wav like Eggman.EXE

### ISSUE THREAD

**Issue by PoohChannelYT** [Chimmiemdp/FNF-FANMADE-CHROMATIC-SCALES#3]
Pls fix it i have to make triple trouble cover

**Comment by Chimmiemdp** [comment]
I would have to convert the fst into a wav for all of those, They were originally .fst files anyways, Most cover makers use fl studio so it's compatable for the majority of people

**Comment by PoohChannelYT** [comment]
Ok thanks i am using fl sudio mobile anyway
