### ISSUE TITLE
Annie Chromatic Scale has Piano Sound

### ISSUE THREAD

**Issue by CaptainGame17** [Chimmiemdp/FNF-FANMADE-CHROMATIC-SCALES#4]
For some reason, Annie's chromatic scale has a piano sound as part of the chromatic scale.

**Comment by Chimmiemdp** [comment]
Yeah idk what's with that, lemme fix it rq

**Comment by Chimmiemdp** [comment]
Sorry for taking so long lmao but i just fixed it, Sorry about that

**Comment by fireredfan7** [comment]
> Sorry for taking so long lmao but i just fixed it, Sorry about that

@Chimmie-mpeg The piano notes are still in there.
