### ISSUE TITLE
I can’t use ur chroms

### ISSUE THREAD

**Issue by Fnflover76** [Chimmiemdp/FNF-FANMADE-CHROMATIC-SCALES#7]
How can I use fst files on mobile

**Comment by Chimmiemdp** [comment]
you can't

**Comment by Fnflover76** [comment]
Maybe you can make a thing where you can use the chroms on iOS and android

**Comment by Chimmiemdp** [comment]
I would have to convert the fst to an audio file for them to be usable, But also i'm pretty sure you can't use chromatics on mobile unless you slice every individual note

**Comment by Fnflover76** [comment]
That would take a loooooooooooooooooooong time

**Comment by Fnflover76** [comment]
But you can still convert the fst to audio file

**Comment by Chimmiemdp** [comment]
I don't think i did it to all of them but i did convert alot to audio files
